# Generated by Django 5.0.4 on 2024-04-15 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservice',
            name='img',
            field=models.ImageField(default='service/service.jpg', upload_to='services', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
