# Generated by Django 5.0.3 on 2024-05-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerservice_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerservice',
            options={},
        ),
    ]
